# Generated by Django 3.2.6 on 2021-08-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210816_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_image',
            new_name='profile_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
