# Generated by Django 3.1.8 on 2021-08-24 07:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210824_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='images'),
        ),
    ]
